### ISSUE TITLE
ara_api role on fedora could not detect package manager 

### ISSUE THREAD

**Issue by yodatak** [ansible-community/ara#42] opened 2019-05-17 13:54 UTC
The use of of auto make it bug on my fedora 30 
TASK [ara_api : Get list of installed packages] **********************************************************************************************************************************************************************************************
task path: /home/YC588F8N/ara/ara-feature-1.0/roles/ara_api/tasks/pre-requirements.yaml:32
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: YC588F8N
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1558101442.807949-53175802335807 `" && echo ansible-tmp-1558101442.807949-53175802335807="` echo /tmp/ansible-tmp-1558101442.807949-53175802335807 `" ) && sleep 0'
Using module file /home/X/.ara/virtualenv/lib64/python3.7/site-packages/ansible/modules/packaging/os/package_facts.py
<127.0.0.1> PUT /home/X/.ansible/tmp/ansible-local-4634b0t1_ln9/tmprp6ve_5_ TO /tmp/ansible-tmp-1558101442.807949-53175802335807/AnsiballZ_package_facts.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1558101442.807949-53175802335807/ /tmp/ansible-tmp-1558101442.807949-53175802335807/AnsiballZ_package_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/X/.ara/virtualenv/bin/python3 /tmp/ansible-tmp-1558101442.807949-53175802335807/AnsiballZ_package_facts.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1558101442.807949-53175802335807/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "manager": [
                "auto"
            ],
            "strategy": "first"
        }
    },
    "msg": "Could not detect a supported package manager from the following list: ['portage', 'pkg', 'apt', 'rpm']"
}

**Comment by dmsimard** [comment] 2019-05-17 17:33
@yodatak in my experience, that issue is because the python interpreter from your virtual environment isn't inheriting from your system packages and so it doesn't have access to python-yum (or python-dnf, or libselinux...)

I'd love to find a solution for this.

**Comment by dmsimard** [comment] 2019-05-21 15:06
@yodatak are you able to reproduce the issue with a virtualenv that inherits system packages ?
Like this: ``python3 -m venv --system-site-packages /path/to/venv``

**Comment by dmsimard** [comment] 2019-06-07 13:02
Going to close this issue. Feel free to re-open if it is still relevant.

**Closed by dmsimard** 2019-06-07 13:02 UTC
Labels: ansible roles
