### ISSUE TITLE
Running ara_api playbook fails on install_ara

### ISSUE THREAD

**Issue by rndmh3ro** [ansible-community/ara#43] opened 2019-05-20 11:23 UTC
# Problem

Installing ara on Ubuntu 18.04 with: 
```bash
> ubuntu:~/ara-1.0.0b1/playbooks$ cat hosts
127.0.0.1
> ansible-playbook -i hosts ara_web.yaml -K
```

fails with: 

```bash
TASK [ara_api : Prepare git repository for ara] **********************************************************************
changed: [127.0.0.1]

TASK [ara_api : Install ara] *****************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to find required executable virtualenv in paths: /usr
/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"}
        to retry, use: --limit @/home/basti/ara-1.0.0b1/playbooks/ara_api.retry

PLAY RECAP ***********************************************************************************************************
127.0.0.1                  : ok=12   changed=5    unreachable=0    failed=1
```

# Resolution

Change the install ara task to look like this.
Since Python 3 is required for ara and on Ubuntu the binary `virtualenv` does not exist, I guess this should be fine. However I did not test in on other operating systems. I can provide a PR for it.

```yaml
- name: Install ara
  pip:
    name: "{{ ara_api_source_checkout }}[server]"
    state: present
    virtualenv: "{{ ara_api_venv | bool | ternary(ara_api_venv_path, omit) }}"
    #virtualenv_python: python3
    virtualenv_command: "/usr/bin/python3 -m venv"
```

# Additional data

ARA-release: `1.0.0b1`

OS:
```
VERSION="18.04.2 LTS (Bionic Beaver)"
```

Python:
```
ubuntu:~/ara-1.0.0b1/playbooks$ python --version
Python 2.7.15rc1
ubuntu:~/ara-1.0.0b1/playbooks$ which python
/usr/bin/python
```

**Comment by dmsimard** [comment] 2019-05-21 15:05
@rndmh3ro I remember this being problematic and trying both ``virtualenv_python`` and ``virtualenv_command`` and needing to settle on ``virtualenv_python`` but I forget why at this time.

I've sent a test patch to replace virtualenv_python with virtualenv_command here: https://review.opendev.org/660420

**Comment by dmsimard** [comment] 2019-05-21 15:50
Oh, yeah, this is why (from [CI](http://logs.openstack.org/20/660420/1/check/ansible-role-ara-api-ubuntu/fae8f2f/ara-report/)):
```
stdout: Processing /home/zuul/.ara/git/ara
Collecting pbr!=2.1.0,>=2.0.0 (from ara==1.0.0.0b2.dev7)
  Downloading http://mirror.dfw.rax.openstack.org/pypifiles/packages/07/3e/22d1d35a4b51706ca3590c54359aeb5fa7ea60df46180143a3ea13d45f29/pbr-5.2.0-py2.py3-none-any.whl (107kB)
Collecting requests>=2.14.2 (from ara==1.0.0.0b2.dev7)
  Downloading http://mirror.dfw.rax.openstack.org/pypifiles/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl (57kB)
Collecting Django>=2.1.5 (from ara==1.0.0.0b2.dev7)
  Downloading http://mirror.dfw.rax.openstack.org/pypifiles/packages/b1/1d/2476110614367adfb079a9bc718621f9fc8351e9214e1750cae1832d4090/Django-2.2.1-py3-none-any.whl (7.4MB)
Collecting django-cors-headers (from ara==1.0.0.0b2.dev7)

:stderr: Exception:
Traceback (most recent call last):
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/home/zuul/.ara/virtualenv/lib/python3.6/site-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/home/zuul/.ara/virtualenv/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
pip._vendor.requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://mirror.dfw.rax.openstack.org/wheel/ubuntu-18.04-x86_64/django-cors-headers/
```

This occurs only on Ubuntu and doesn't reproduce on Fedora.
I've held a CI node to troubleshoot this further.

**Comment by dmsimard** [comment] 2019-05-21 16:17
Ok so the problem that makes pip give up immediately is resolved by https://github.com/pypa/pip/pull/6367 but it hasn't made it's way to updated packages everywhere yet.

We hit this problem in CI because the virtual machines are set up to use local pypi/wheel mirrors, from ``/etc/pip.conf``:
```ini
# Ansible managed
[global]
timeout = 60
index-url = http://mirror.iad.rax.openstack.org/pypi/simple
extra-index-url = http://mirror.iad.rax.openstack.org/wheel/ubuntu-18.04-x86_64
trusted-host = mirror.iad.rax.openstack.org
```

I sent https://review.opendev.org/#/c/660445/ to remove the extra wheel mirror and rebased https://review.opendev.org/660420 on top of it.

**Comment by dmsimard** [comment] 2019-05-21 20:09
This has been fixed and will land in beta2.

**Closed by dmsimard** 2019-05-21 20:09 UTC
Labels: ansible roles, bug
