### ISSUE TITLE
API not receiving hosts. 

### ISSUE THREAD

**Issue by adahlmanpinterest** [ansible-community/ara#87] opened 2019-10-31 04:59 UTC
## What component is this about ?
API Client

## What is your ARA installation like ?
Ara api is installed on an its own aws instance behind an ELB. 
The ara-web server is able to talk to the api webserver , ara.pinadmin.com and araweb.pinadmin.com. 

The elb is pointing from 80-8000. And allowing all traffic from our RFC 1819 space. 

## What is happening ?
Currently running test ansible runs and the API server isn't picking up the request. Here is the ansible.cfg:

```
[defaults]
inventory = /etc/ansible/inventory/production.yaml
remote_tmp = /etc/ansible/tmp
local_tmp = /etc/ansible/tmp
log_path = /var/log/ansible.log
callback =  ara
callback_type = notification
[ara]
api_client = http
api_server = http://ara.pinadmin.com
api_username = joe
api_password = joe12345678
api_timeout = 15
ignored_facts = '["ansible_env", "ansible_all_ipv4_addresses"]'
ignored_arguments = '["extra_vars", "vault_password_files"]'
```

playbook:
```
 - name: Run playbook for all hosts
    hosts: all 
  connection: local
  vars_files:
    - /etc/ansible/vars/basevars.yml
  become: true
  vars:
    ara_playbook_name: base
    ara_playbook_labels:
        - base-test
  roles:
   - logrotate
```

settings.yaml 
```default:
  ALLOWED_HOSTS: !!python/object/new:box.BoxList
    listitems:
    - ::1
    - 127.0.0.1
    - localhost
    - ara.mars.pinadmin.com
    - ara.pinadmin.com
    state:
      box_class: &id001 !!python/name:box.Box ''
      box_options: {}
      box_org_ref: 140525303662472
  BASE_DIR: /opt/ara/.ara/server
  CORS_ORIGIN_ALLOW_ALL: true
  CORS_ORIGIN_WHITELIST: !!python/object/new:box.BoxList
    listitems:
    - http://127.0.0.1:8000
    - http://ara.pinadmin.com:8000
    - http://ara.mars.pinadmin.com:8000
    - http://araweb.pinadmin.com:3000
    - http://araweb.mars.pinadmin.com:3000
    - http://araweb.pinadmin.com
    - http://araweb.mars.pinadmin.com
    - http://10.245.66.205:3000/
```

 The security groups are allowing traffic in as I'm able to curl the api server from all my servers.  Am I missing anything Ansible wise that would cause these requests to not reach the api?

## What should be happening ?
Ansible playbooks should be reporting to the API.

**Comment by dmsimard** [comment] 2019-10-31 14:25
Hi @adahlmanpinterest and thanks for the detailed report :+1:

I think the issue is in the ``ansible.cfg`` file:
```
[defaults]
# [...]
callback =  ara
callback_type = notification
```

Should be something like this instead:
```
[defaults]
# [...]
callback_plugins = /path/to/ara/plugins/callback
```

You can find the exact path to the ara callback plugin with a helper command:
```
$ python3 -m ara.setup.callback_plugins
/usr/lib/python3.7/site-packages/ara/plugins/callback
```

More info in docs: https://ara.readthedocs.io/en/latest/ansible-configuration.html#using-setup-helper-modules

**Comment by dmsimard** [comment] 2019-10-31 14:35
Unrelated but FYI those ``!!python/object/new:box.BoxList`` kind of declarations are new to me and I don't know what they're about yet -- they didn't use to be there. I've opened an issue to inquire about them: https://github.com/rochacbruno/dynaconf/issues/257

**Comment by dmsimard** [comment] 2019-10-31 17:07
@adahlmanpinterest the following graph might be helpful to understand how the components work: https://ara.readthedocs.io/en/latest/faq.html#how-does-ara-record-data-from-ansible

The ``callback_plugins`` Ansible configuration tells Ansible where it can find callback plugins. Providing the path to the location where the ARA callback plugin is located is what makes Ansible load the ARA callback and the ARA callback is what sends data to the API server.

The callback plugin can then be configured to send data remotely which you are already doing in your ``[ara]`` block.

**Comment by adahlmanpinterest** [comment] 2019-10-31 21:20
Updated to the following.
```
[defaults]
inventory = /etc/ansible/inventory/production.yaml
remote_tmp = /etc/ansible/tmp
local_tmp = /etc/ansible/tmp
log_path = /var/log/ansible.log
callback_plugins=/home/ara/.local/lib/python3.6/site-packages/ara/plugins/callback
action_plugins=/home/ara/.local/lib/python3.6/site-packages/ara/plugins/action
[ara]
api_client = http
api_server = https://ara-api.pinadmin.com
api_username = test
api_password =test
api_timeout = 15
ignored_facts = '["ansible_env", "ansible_all_ipv4_addresses"]'
ignored_arguments = '["extra_vars", "vault_password_files"]'
```

`sudo ansible-playbook playbook/base.yml --limit ${HOSTNAME}`

Still dont see any traffic into the box. Im able to curl from host running the playbook and the ara-web is polling the api just fine.

**Comment by dmsimard** [comment] 2019-11-01 14:10
@adahlmanpinterest your ``ansible.cfg`` file looks good to me.
Is it located in ``/etc/ansible/ansible.cfg`` on the server where Ansible is running from ?

Although Ansible 2.5.1 has long been [EOL](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html) and we no longer have tests for it, I've just tested it and it still works.

You can tell if the callback is properly loaded by running with increased verbosity (``ansible-playbook -vvvv``):
```
$ pip install ara ansible==2.5.1
$ export ANSIBLE_CALLBACK_PLUGINS=$(python3 -m ara.setup.callback_plugins)
$ ansible-playbook tests/integration/smoke.yaml -vvvv
ansible-playbook 2.5.1
  config file = None
  configured module search path = ['/home/dmsimard/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dmsimard/dev/git/ansible-community/ara/.tox/py37/lib/python3.7/site-packages/ansible
  executable location = /home/dmsimard/dev/git/ansible-community/ara/.tox/py37/bin/ansible-playbook
  python version = 3.7.4 (default, Jul  9 2019, 16:32:37) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]
No config file found; using defaults
setting up inventory plugins
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /home/dmsimard/dev/git/ansible-community/ara/.tox/py37/lib/python3.7/site-packages/ansible/plugins/callback/default.py
# This -----> Loading callback plugin ara_default of type awesome, v2.0 from /home/dmsimard/dev/git/ansible-community/ara/ara/plugins/callback/ara_default.py
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  No migrations to apply.

PLAYBOOK: smoke.yaml **************************************************************************************************************************************************************************
3 plays in tests/integration/smoke.yaml
[...]
```

**Comment by adahlmanpinterest** [comment] 2019-11-01 21:51
@dmsimard Stupid question, does ara need to be installed on every machine that needs to talk to the api?

**Comment by adahlmanpinterest** [comment] 2019-11-01 22:24
Got it working! Removed the apt ansible, installed ansible with python3, installed ara via ```python3 -m pip install ara``` exported the callbacks. Bingo Thanks! The onlything now is its reporting the group in inventory as a host. but looks great!

**Comment by dmsimard** [comment] 2019-11-01 23:12
> Got it working!

🎉

> The only thing now is its reporting the group in inventory as a host.

This is already fixed by this issue: https://github.com/ansible-community/ara/issues/79

You can do ``pip install --pre ara`` to try out the beta release of 1.2.0 that contains the fix.

**Comment by dmsimard** [comment] 2019-11-02 01:22
> @dmsimard Stupid question, does ara need to be installed on every machine that needs to talk to the api?

Missed your question.
The ara callback needs to be installed wherever Ansible is running from.

**Comment by dmsimard** [comment] 2019-11-02 01:23
Closing this since you're up and running now.

**Closed by dmsimard** 2019-11-02 01:23 UTC
Labels: question
