### ISSUE TITLE
Error while running ARA server on Alpine linux

### ISSUE THREAD

**Issue by Rabieezz** [ansible-community/ara#213] opened 2021-03-08 09:40 UTC
I am trying to install the latest version of the Ansible Records Analyzer server on an alpine Linux I made sure that all requirements are well installed ( Django, GCC,python3, Pypi, ansible) the install went well except for a warning about the absence of root PATH on the PATH variable which I fixed:
The warning :
```
  WARNING: The script pbr is installed in '/root/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

```
The fix:

```
~ # export PATH=/root/.local/bin:$PATH
```
So following the install [guide][1] on this step that intends to run the server I have an avalanche of errors as if the run command doesn't find the needed components to be executed although I'm sure all the components are installed :

```shell
~ # ara-manage runserver
[ara] No setting found for SECRET_KEY. Generating a random key...
Traceback (most recent call last):
  File "/root/.local/bin/ara-manage", line 8, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.8/site-packages/ara/server/__main__.py", line 41, in main
    if not os.path.exists(settings.ARA_SETTINGS):
  File "/root/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.8/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/.local/lib/python3.8/site-packages/ara/server/settings.py", line 263, in <module>
    ALLOWED_HOSTS=ALLOWED_HOSTS.to_list(),
AttributeError: 'list' object has no attribute 'to_list'
```
What could be the reason behind this behavior?
 

  [1]: https://ara.readthedocs.io/en/latest/getting-started.html

**Comment by dmsimard** [comment] 2021-03-08 12:45
Hi @Rabieezz, dynaconf manages settings and it looks like a new version of it released recently: https://github.com/ansible-community/ara/issues/212

For now you should be able to work around the issue by pinning dynaconf to the previous release.

I will look into this soon but in the meantime I will close the issue since it's a duplicate of https://github.com/ansible-community/ara/issues/212.

**Closed by dmsimard** 2021-03-08 12:45 UTC
