### ISSUE TITLE
Possible bug here with ansible.builtin.setup not being picked up ? host facts empty.

### ISSUE THREAD

**Issue by cocoonkid** [ansible-community/ara#497] opened 2023-07-05 10:25 UTC
## What is the issue ?

Even though facts are correctly gathered to the custom dir ./facts they are not correctly picked up by ara.

gather_facts: false is set for my playbook so I can run a task that checks which ports are reachable and then assigns  ansible_user and ansible_port  according to the results.

then after these have been  set I run

    - name: Run deferred setup to gather facts
      ansible.builtin.setup:
      delegate_to: "{{ inventory_hostname }}"
      delegate_facts: true

but 

![image](https://github.com/ansible-community/ara/assets/43231640/f410bd70-47e2-4b88-98f7-78894229d6c2)

I tried setting       delegate_facts: false but no dice.

Other references to the problem:
#397 #400 

## What should be happening ?

I should be able to see the host facts in the ara dashboard.

**Comment by hille721** [comment] 2023-07-05 11:30
Which ara version are you using? This should be already fixed.

What is the reason for this `delegate_to: {{ inventory_hostname }}`?
Imo this is not needed as this is the default behavior. But this could be a reason why it is not probably reported in Ara.

**Comment by hille721** [comment] 2023-07-06 14:39
> ara 3.2.20.

mmh, this seems to be not the ara version as the current version is 1.6.1

Using `gather_facts: false` and triggering the facts gathering manually via setup module is not a problem for reporting in Ara and should work.

I really guess that the problem is the double delegation you are doing:
If I understand you correctly your playbook runs on serverA, then you delegate to localhost and then you delegate to serverA. Thus ara does not understand that the delegation to serverA is the same server as where the playbook was running.

Imo a better design would be to only delegate the tasks to localhost which should run there instead of delegating the whole role and using `delegate_to: {{ inventory_hostname }}`.
You could try that as a quick workaround.

> lovely greetings to the nicest city in the world btw 

thanks :) but currently I'm not there but on vacation. That's why I'm also not having time to reproduce your issue.

**Comment by hille721** [comment] 2023-07-06 14:50
one other thing you could try: don't set `gather_facts: true`. 
As "any facts gathered by a delegated task are assigned by default to the inventory_hostname" (https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_delegation.html#delegating-facts).
I guess then the reporting in Ara should work as well.

**Comment by cocoonkid** [comment] 2023-07-19 11:21
@hille721 

Thanks so much!  That made it work :)

**Comment by dmsimard** [comment] 2023-07-29 20:31
I'll close this issue considering it works for you @cocoonkid.

For the purpose of future readers, what was the actual issue or fix ?

![wisdom_of_the_ancients](https://github.com/ansible-community/ara/assets/1291204/88488bff-5c71-4a97-b39e-8a9a5e512f13)

It also seemed to me at first glance like an occurance of a bug we once had but was fixed with https://github.com/ansible-community/ara/pull/400 but I'm not sure.

Thanks,

**Closed by dmsimard** 2023-07-29 20:31 UTC
