### ISSUE TITLE
API server no longer accept default format for `ALLOWED_HOSTS`

### ISSUE THREAD

**Issue by hvtuananh** [ansible-community/ara#115] opened 2020-02-14 20:33 UTC
## What component is this about ?
API server

## What is happening ?
Running API server with `ARA_ALLOWED_HOSTS='["127.0.0.1", "localhost", "::1"]'` environment variable now produce an error:

```
File "{...}/ara/server/settings.py", line 248, in <module>
    ALLOWED_HOSTS=ALLOWED_HOSTS.to_list(),
AttributeError: 'list' object has no attribute 'to_list'
```

Ref commit: https://github.com/ansible-community/ara/commit/df3bace703ea0c8bc3cbf6946444848c4cfaa61d

## What should be happening ?
API server should accept this format, or the doc should specify an alternative way of configuring `ALLOWED_HOSTS`

**Comment by dmsimard** [comment] 2020-04-14 19:33
Hi @hvtuananh and thanks for the issue.
I wasn't able to look into this until now but wanted to know if you were still able to reproduce this issue ?

For example, if I run the following, it works:
```
$ export ARA_ALLOWED_HOSTS='["127.0.0.1", "localhost", "::1"]'
$ ara-manage runserver
2020-04-14 15:31:21,941 INFO django.utils.autoreload: Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 14, 2020 - 15:31:22
Django version 2.2.9, using settings 'ara.server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[14/Apr/2020 15:31:27] "GET / HTTP/1.1" 200 430818
[14/Apr/2020 15:31:27] "GET /static/css/patternfly.min.css HTTP/1.1" 304 0
[14/Apr/2020 15:31:27] "GET /static/css/ara.css HTTP/1.1" 304 0
[14/Apr/2020 15:31:27] "GET /static/images/logo.svg HTTP/1.1" 200 6129
[...]
```

And then, if I put a wrong value on purpose:
```
$ export ARA_ALLOWED_HOSTS='["10.10.10.10"]'
$ .tox/ansible-integration/bin/ara-manage runserver
2020-04-14 15:32:59,882 INFO django.utils.autoreload: Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 14, 2020 - 15:33:00
Django version 2.2.9, using settings 'ara.server.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2020-04-14 15:33:02,441 ERROR django.security.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
2020-04-14 15:33:02,469 WARNING django.request: Bad Request: /
[14/Apr/2020 15:33:02] "GET / HTTP/1.1" 400 26
```

I think we could do a better job at documenting how to set the variables, though, because there was another issue about a user struggling with ALLOWED_HOSTS: https://github.com/ansible-community/ara/issues/108

**Comment by hvtuananh** [comment] 2020-04-21 18:24
Looks like I was using an old version of dynaconf (2.0.3 vs 2.2.3). I can no longer reproduce this issue. Sorry for the false alarm.

**Comment by dmsimard** [comment] 2020-04-21 18:39
@hvtuananh Thanks for getting back to us ! I will close this issue then.
Feel free to report if there's anything else.

**Closed by dmsimard** 2020-04-21 18:39 UTC
Labels: bug, config, needs information
